window.INGREDIENT_FAMILY_PATTERNS = [
  ['eau', /\beau\b/],
  ['sel', /\bsel\b/],
  ['poivre', /\bpoivre\b/],
  ['sucre', /\bsucre\b/],
  ['cassonade', /\bcassonade\b/],
  ['sucre glace', /\bsucre glace\b/],
  ['sucre vanille', /\bsucre vanille\b/],
  ['miel', /\bmiel\b/],
  ['sirop erable', /\bsirop erable\b/],
  ['sirop agave', /\bsirop agave\b/],
  ['vanille', /\bvanille\b/],
  ['cannelle', /\bcannelle\b/],
  ['muscade', /\bmuscade\b/],
  ['cardamome', /\bcardamome\b/],
  ['clou girofle', /\bclou girofle\b/],
  ['gingembre', /\bgingembre\b/],
  ['curcuma', /\bcurcuma\b/],
  ['cumin', /\bcumin\b/],
  ['coriandre', /\bcoriandre\b/],
  ['paprika', /\bpaprika\b/],
  ['piment', /\bpiment\b/],
  ['curry', /\bcurry\b/],
  ['garam masala', /\bgaram masala\b/],
  ['ras el hanout', /\bras el hanout\b/],
  ['zaatar', /\bzaatar\b/],
  ['sumac', /\bsumac\b/],
  ['herbe provence', /\bherbe provence\b/],
  ['thym', /\bthym\b/],
  ['laurier', /\blaurier\b/],
  ['origan', /\borigan\b/],
  ['romarin', /\bromarin\b/],
  ['basilic', /\bbasilic\b/],
  ['persil', /\bpersil\b/],
  ['ciboulette', /\bciboulette\b/],
  ['menthe', /\bmenthe\b/],
  ['aneth', /\baneth\b/],
  ['estragon', /\bestragon\b/],
  ['sauge', /\bsauge\b/],
  ['vinaigre balsamique', /\bvinaigre balsamique\b/],
  ['vinaigre cidre', /\bvinaigre cidre\b/],
  ['vinaigre riz', /\bvinaigre riz\b/],
  ['vinaigre', /\bvinaigre\b/],
  ['huile olive', /\bhuile olive\b/],
  ['huile coco', /\bhuile coco\b/],
  ['huile sesame', /\bhuile sesame\b/],
  ['huile tournesol', /\bhuile tournesol\b/],
  ['huile colza', /\bhuile colza\b/],
  ['huile noisette', /\bhuile noisette\b/],
  ['beurre', /\bbeurre\b/],
  ['margarine', /\bmargarine\b/],
  ['moutarde', /\bmoutarde\b/],
  ['mayonnaise', /\bmayonnaise\b/],
  ['ketchup', /\bketchup\b/],
  ['sauce tomate', /\bsauce tomate\b/],
  ['puree tomate', /\bpuree tomate\b/],
  ['concentre tomate', /\bconcentre tomate\b/],
  ['coulis tomate', /\bcoulis tomate\b/],
  ['tomate sechee', /\btomate sech/],
  ['tomate cerise', /\btomate cerise\b/],
  ['tomate', /\btomate\b/],
  ['poivron', /\bpoivron\b/],
  ['piment doux', /\bpiment doux\b/],
  ['courgette', /\bcourgette\b/],
  ['aubergine', /\baubergine\b/],
  ['concombre', /\bconcombre\b/],
  ['cornichon', /\bcornichon\b/],
  ['carotte', /\bcarotte\b/],
  ['patate douce', /\bpatate douce\b/],
  ['pomme terre', /\bpomme terre\b/],
  ['pomme de terre', /\bpomme de terre\b/],
  ['navet', /\bnavet\b/],
  ['panais', /\bpanais\b/],
  ['radis', /\bradis\b/],
  ['betterave', /\bbetterave\b/],
  ['fenouil', /\bfenouil\b/],
  ['celeri', /\bceleri\b/],
  ['celeri rave', /\bceleri rave\b/],
  ['branche celeri', /\bbranche celeri\b/],
  ['poireau', /\bpoireau\b/],
  ['oignon rouge', /\boignon rouge\b/],
  ['oignon nouveau', /\boignon nouveau\b/],
  ['oignon cebette', /\boignon cebette\b/],
  ['oignon', /\boignon\b/],
  ['echalote', /\bechalote\b/],
  ['ail', /\bail\b/],
  ['aillet', /\baillet\b/],
  ['gingembre frais', /\bgingembre frais\b/],
  ['brocoli', /\bbrocoli\b/],
  ['chou fleur', /\bchou fleur\b/],
  ['chou kale', /\bkale\b/],
  ['chou rouge', /\bchou rouge\b/],
  ['chou blanc', /\bchou blanc\b/],
  ['chou vert', /\bchou vert\b/],
  ['chou', /\bchou\b/],
  ['epinard', /\bepinard\b/],
  ['blette', /\bblette\b/],
  ['salade', /\bsalade\b/],
  ['laitue', /\blaitue\b/],
  ['roquette', /\broquette\b/],
  ['mache', /\bmache\b/],
  ['endive', /\bendive\b/],
  ['asperge', /\basperge\b/],
  ['artichaut', /\bartichaut\b/],
  ['petit pois', /\bpetit pois\b/],
  ['haricot vert', /\bharicot vert\b/],
  ['mais', /\bmais\b/],
  ['olive', /\bolive\b/],
  ['avocat', /\bavocat\b/],
  ['citron vert', /\bcitron vert\b/],
  ['citron', /\bcitron\b/],
  ['orange', /\borange\b/],
  ['pamplemousse', /\bpamplemousse\b/],
  ['clementine', /\bclementine\b/],
  ['mandarine', /\bmandarine\b/],
  ['pomme', /\bpomme\b/],
  ['poire', /\bpoire\b/],
  ['banane', /\bbanane\b/],
  ['fraise', /\bfraise\b/],
  ['framboise', /\bframboise\b/],
  ['myrtille', /\bmyrtille\b/],
  ['mure', /\bmure\b/],
  ['cassis', /\bcassis\b/],
  ['groseille', /\bgroseille\b/],
  ['cerise', /\bcerise\b/],
  ['abricot', /\babricot\b/],
  ['peche', /\bpeche\b/],
  ['nectarine', /\bnectarine\b/],
  ['prune', /\bprune\b/],
  ['raisin', /\braisin\b/],
  ['figue', /\bfigue\b/],
  ['datte', /\bdatte\b/],
  ['pruneau', /\bpruneau\b/],
  ['ananas', /\bananas\b|\bananas\b|\bananas/],
  ['mangue', /\bmangue\b/],
  ['kiwi', /\bkiwi\b/],
  ['melon', /\bmelon\b/],
  ['pasteque', /\bpasteque\b/],
  ['noix coco', /\bnoix coco\b/],
  ['lait coco', /\blait coco\b/],
  ['creme coco', /\bcreme coco\b/],
  ['coco rapee', /\bcoco rapee\b/],
  ['coco', /\bcoco\b/],
  ['pois chiche', /\bpois chiche\b/],
  ['lentille corail', /\blentille corail\b/],
  ['lentille verte', /\blentille verte\b/],
  ['lentille', /\blentille\b/],
  ['haricot rouge', /\bharicot rouge\b/],
  ['haricot noir', /\bharicot noir\b/],
  ['haricot blanc', /\bharicot blanc\b/],
  ['haricot', /\bharicot\b/],
  ['feve', /\bfeve\b/],
  ['edamame', /\bedamame\b/],
  ['tofu soyeux', /\btofu soyeux\b/],
  ['tofu fume', /\btofu fume\b/],
  ['tofu', /\btofu\b/],
  ['tempeh', /\btempeh\b/],
  ['seitan', /\bseitan\b/],
  ['proteine soja', /\bproteine soja\b|\bpst\b/],
  ['soja', /\bsoja\b/],
  ['lait soja', /\blait soja\b/],
  ['yaourt soja', /\byaourt soja\b/],
  ['creme soja', /\bcreme soja\b/],
  ['riz', /\briz\b/],
  ['riz basmati', /\briz basmati\b/],
  ['riz complet', /\briz complet\b/],
  ['riz rond', /\briz rond\b/],
  ['quinoa', /\bquinoa\b/],
  ['boulgour', /\bboulgour\b/],
  ['semoule', /\bsemoule\b/],
  ['couscous', /\bcouscous\b/],
  ['polenta', /\bpolenta\b/],
  ['orge', /\borge\b/],
  ['millet', /\bmillet\b/],
  ['sarrasin', /\bsarrasin\b/],
  ['avoine', /\bavoine\b/],
  ['flocon avoine', /\bflocon avoine\b/],
  ['muesli', /\bmuesli\b/],
  ['granola', /\bgranola\b/],
  ['pain', /\bpain\b/],
  ['mie pain', /\bmie pain\b/],
  ['chapelure', /\bchapelure\b/],
  ['wrap', /\bwrap\b/],
  ['tortilla', /\btortilla\b/],
  ['pate filo', /\bpate filo\b/],
  ['pate brisee', /\bpate brisee\b/],
  ['pate feuilletee', /\bpate feuilletee\b/],
  ['pate', /\bpate\b/],
  ['nouille', /\bnouille\b/],
  ['lasagne', /\blasagne\b/],
  ['gnocchi', /\bgnocchi\b/],
  ['farine ble', /\bfarine ble\b/],
  ['farine riz', /\bfarine riz\b/],
  ['farine pois chiche', /\bfarine pois chiche\b/],
  ['farine mais', /\bfarine mais\b/],
  ['farine maisena', /\bmaizena\b|\bmaisena\b/],
  ['farine amande', /\bfarine amande\b/],
  ['farine coco', /\bfarine coco\b/],
  ['farine', /\bfarine\b/],
  ['levure chimique', /\blevure chimique\b/],
  ['levure boulanger', /\blevure boulanger\b/],
  ['levure maltee', /\blevure maltee\b/],
  ['bicarbonate', /\bbicarbonate\b/],
  ['oeuf', /\boeuf\b/],
  ['blanc oeuf', /\bblanc oeuf\b/],
  ['jaune oeuf', /\bjaune oeuf\b/],
  ['lait amande', /\blait amande\b/],
  ['lait avoine', /\blait avoine\b/],
  ['lait riz', /\blait riz\b/],
  ['lait', /\blait\b/],
  ['yaourt', /\byaourt\b/],
  ['fromage blanc', /\bfromage blanc\b/],
  ['creme fraiche', /\bcreme fraiche\b/],
  ['creme liquide', /\bcreme liquide\b/],
  ['creme', /\bcreme\b/],
  ['fromage chevre', /\bchevre\b/],
  ['feta', /\bfeta\b/],
  ['mozzarella', /\bmozzarella\b/],
  ['parmesan', /\bparmesan\b/],
  ['comte', /\bcomte\b/],
  ['gruyere', /\bgruyere\b/],
  ['emmental', /\bemmental\b/],
  ['ricotta', /\bricotta\b/],
  ['mascarpone', /\bmascarpone\b/],
  ['fromage frais', /\bfromage frais\b/],
  ['beurre cacahuete', /\bbeurre cacahuete\b/],
  ['cacahuete', /\bcacahuete\b/],
  ['amande', /\bamande\b/],
  ['noisette', /\bnoisette\b/],
  ['noix cajou', /\bnoix cajou\b/],
  ['noix', /\bnoix\b/],
  ['pistache', /\bpistache\b/],
  ['pecan', /\bpecan\b/],
  ['pignon', /\bpignon\b/],
  ['graine sesame', /\bgraine sesame\b|\bsesame\b/],
  ['graine courge', /\bgraine courge\b/],
  ['graine tournesol', /\bgraine tournesol\b/],
  ['graine chia', /\bgraine chia\b/],
  ['graine lin', /\bgraine lin\b/],
  ['raisin sec', /\braisin sec\b/],
  ['abricot sec', /\babricot sec\b/],
  ['cranberry', /\bcranberry\b/],
  ['datte', /\bdatte\b/],
  ['chocolat noir', /\bchocolat noir\b/],
  ['chocolat blanc', /\bchocolat blanc\b/],
  ['chocolat lait', /\bchocolat lait\b/],
  ['chocolat', /\bchocolat\b/],
  ['cacao', /\bcacao\b/],
  ['cafe', /\bcafe\b/],
  ['the', /\bthe\b/],
  ['bouillon legume', /\bbouillon legume\b/],
  ['bouillon', /\bbouillon\b/],
  ['levure', /\blevure\b/],
  ['sauce soja', /\bsauce soja\b/],
  ['tamari', /\btamari\b/],
  ['miso', /\bmiso\b/],
  ['tahini', /\btahini\b/],
  ['houmous', /\bhoumous\b/],
  ['pesto', /\bpesto\b/],
  ['corn flake', /\bcorn flake\b/],
];
